# Generated by Django 3.2.7 on 2021-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
