# Generated by Django 3.2.7 on 2021-09-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_person_payment_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
