# Generated by Django 3.2.5 on 2021-08-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210803_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='user',
        ),
    ]
