# Generated by Django 3.2.7 on 2021-10-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('map', '0002_parkinglot_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='vaild_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vaild_start',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.personal'),
        ),
    ]
