# Generated by Django 3.2.7 on 2021-10-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_user_ticket_perosnal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='perosnal',
            new_name='personal',
        ),
    ]
