# Generated by Django 3.2.5 on 2021-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_parkinglot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
