# Generated by Django 3.2.7 on 2021-10-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('map', '0005_rename_perosnal_ticket_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.personal'),
            preserve_default=False,
        ),
    ]
