# Generated by Django 3.2.5 on 2021-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_parkinglot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
