# Generated by Django 3.2.5 on 2021-08-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_parkinglot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='image',
        ),
    ]
