# Generated by Django 3.2.5 on 2021-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_parkinglot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='user',
        ),
    ]
