# Generated by Django 3.2.7 on 2021-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_ticket_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
