# Generated by Django 3.2.7 on 2021-10-10 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_ticket_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 12, 39, 28, 617237)),
            preserve_default=False,
        ),
    ]
