# Generated by Django 3.2.5 on 2021-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_parkinglot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
