# Generated by Django 3.2.7 on 2021-10-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_ticket_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_available',
            new_name='is_vailed',
        ),
    ]
