# Generated by Django 2.2.7 on 2021-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_parkinglot_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='휴대폰 번호')),
                ('auth_number', models.CharField(max_length=30, verbose_name='인증번호')),
            ],
            options={
                'verbose_name_plural': '휴대폰인증 관리 페이지',
                'db_table': 'authentications',
            },
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
