# Generated by Django 3.2.7 on 2021-10-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_personal_deposit'),
        ('map', '0010_rename_is_available_ticket_is_vailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.personal'),
        ),
    ]
