# Generated by Django 2.2.7 on 2021-08-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0011_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='username',
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
