# Generated by Django 3.2.7 on 2021-10-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_personal_deposit'),
        ('map', '0011_alter_ticket_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_vailed',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.personal'),
        ),
    ]
