# Generated by Django 2.2.7 on 2021-08-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20210809_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='end_time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='start_time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaild_start', models.CharField(max_length=10)),
                ('vaild_end', models.CharField(max_length=10)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.ParkingLot')),
            ],
        ),
    ]
