# Generated by Django 3.2.7 on 2021-10-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20211012_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketpayment',
            old_name='spend_mins',
            new_name='spend_sec',
        ),
    ]
