# Generated by Django 3.2.7 on 2021-10-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_personal_deposit'),
        ('map', '0014_rename_spend_mins_ticketpayment_spend_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpayment',
            name='personal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common.personal'),
            preserve_default=False,
        ),
    ]
