# Generated by Django 3.2.7 on 2021-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_ticketpayment_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
