# Generated by Django 3.2.7 on 2021-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20210913_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(default='temp.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
