# Generated by Django 3.2.7 on 2021-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_parkinglot_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='addr_detail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
