# Generated by Django 3.2.7 on 2021-10-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_parkinglot_addr_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='desc',
            new_name='description',
        ),
    ]
