# Generated by Django 3.2.7 on 2021-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20210913_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
