# Generated by Django 3.2.7 on 2021-10-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_remove_parkinglot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
