# Generated by Django 3.2.7 on 2021-09-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='addr',
            field=models.CharField(default='충청북도 청주시 청원구 대성로 298', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.CharField(default='autocreation@shareparking.kr', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='postcode',
            field=models.IntegerField(default=28503),
            preserve_default=False,
        ),
    ]
