# Generated by Django 3.2.7 on 2021-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_auto_20210922_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
