# Generated by Django 3.2.7 on 2021-09-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='uid',
            new_name='pid',
        ),
    ]
