# Generated by Django 3.2.7 on 2021-09-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_rename_uid_payment_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pid',
            new_name='mid',
        ),
    ]
