# Generated by Django 3.2.7 on 2021-09-27 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
