# Generated by Django 3.2.7 on 2021-09-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_payment_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='datetime',
            new_name='created',
        ),
    ]
