# Generated by Django 3.2.7 on 2021-09-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_auto_20210927_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='persona',
            new_name='personal',
        ),
    ]
