# Generated by Django 3.2.7 on 2021-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='deposit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
