# Generated by Django 3.2.7 on 2021-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_personal_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='push_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
