# Generated by Django 3.2.7 on 2021-09-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.personal')),
            ],
        ),
    ]
